/** Song titles for music bingo pool. */

export const BINGO_SONG_TITLES: string[] = [
  "Play That Funky Music — Wild Cherry",
  "Get Up (I Feel Like Being a) Sex Machine — James Brown",
  "Don't Stop 'Til You Get Enough — Michael Jackson",
  "Rapper's Delight — The Sugarhill Gang",
  "Heart of Glass — Blondie",
  "Under Pressure — Queen, David Bowie",
  "Paradise City — Guns N' Roses",
  "This Charming Man — The Smiths",
  "I Wanna Dance with Somebody (Who Loves Me) — Whitney Houston",
  "Umbrella — Rihanna, JAY-Z",
  "Groove Is in the Heart — Deee-Lite",
  "Hey Ya! — Outkast",
  "I See You Baby — Groove Armada",
  "I Follow Rivers (The Magician Remix) — Lykke Li, The Magician",
  "Locked Out of Heaven — Bruno Mars",
  "Where's Your Head At — Basement Jaxx",
  "Ride on Time — Black Box",
  "Little Fluffy Clouds — The Orb",
  "The Only One I Know — The Charlatans",
  "Get Lucky — Daft Punk, Pharrell Williams",
  "You Got the Love — The Source, Candi Staton",
  "Loaded — Primal Scream",
  "Milkshake — Kelis",
  "Get Ur Freak On — Missy Elliott",
  "Girls & Boys — Blur",
  "Smells Like Teen Spirit — Nirvana",
  "Common People — Pulp",
  "Reflektor — Arcade Fire",
  "Firestarter — The Prodigy",
  "Mr. Brightside — The Killers",
  "Take Me Out — Franz Ferdinand",
  "Pumped Up Kicks — Foster the People",
  "Seven Nation Army — The White Stripes",
  "Bohemian Like You — The Dandy Warhols",
  "Time to Pretend — MGMT",
  "Last Nite — The Strokes",
  "I Bet You Look Good on the Dancefloor — Arctic Monkeys",
  "No One Knows — Queens of the Stone Age",
  "Daft Punk Is Playing at My House — LCD Soundsystem",
  "The Man Who Sold the World — Nirvana",
  "Jump — Kris Kross",
  "Hollaback Girl — Gwen Stefani",
  "Dog Days Are Over — Florence and the Machine",
  "Dare — Gorillaz",
  "Dancing On My Own — Robyn",
  "Alright — Supergrass",
  "Lonely Boy — The Black Keys",
  "Praise You — Fatboy Slim",
  "The Passenger — Iggy Pop",
  "Close to me — The Cure",
];
