/** 30 well-known 1970s song titles for music bingo pool (product spec). */

export const BINGO_SONG_TITLES: string[] = [
  "Bohemian Rhapsody — Queen",
  "Hotel California — Eagles",
  "Stayin' Alive — Bee Gees",
  "I Will Survive — Gloria Gaynor",
  "Dream On — Aerosmith",
  "Stairway to Heaven — Led Zeppelin",
  "Dancing Queen — ABBA",
  "Go Your Own Way — Fleetwood Mac",
  "Superstition — Stevie Wonder",
  "Let’s Stay Together — Al Green",
  "Rocket Man — Elton John",
  "American Pie — Don McLean",
  "Smoke on the Water — Deep Purple",
  "Heart of Gold — Neil Young",
  "Lean on Me — Bill Withers",
  "Bridge Over Troubled Water — Simon & Garfunkel",
  "What’s Going On — Marvin Gaye",
  "Born to Run — Bruce Springsteen",
  "Philadelphia Freedom — Elton John",
  "Barracuda — Heart",
  "Carry On Wayward Son — Kansas",
  "The Boys Are Back in Town — Thin Lizzy",
  "You’re So Vain — Carly Simon",
  "Lady Marmalade — Labelle",
  "September — Earth, Wind & Fire",
  "Paranoid — Black Sabbath",
  "The Joker — Steve Miller Band",
  "Listen to the Music — The Doobie Brothers",
  "Roxanne — The Police",
  "Rebel Rebel — David Bowie",
];
